### ISSUE TITLE
BUG[UI]: Missing download button  

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#124] opened 2021-02-23 08:08 UTC
Context: 

- https://open-contracting.health/contracts/159368

Steps

- Data>> Contracts

Actual Result

- The download button is missing on the contract details.

Expected Result

- The contract details must be able to download.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108816494-5ee22300-75de-11eb-9582-cba1d20c622b.png)
![image](https://user-images.githubusercontent.com/45354665/108816518-6a354e80-75de-11eb-8290-8c9e85c4f625.png)

**Comment by jpmckinney** [comment] 2021-09-14 16:35
This is not a bug, but rather an unimplemented feature. I don't get the sense we will be implementing it, so closing.

**Closed by jpmckinney** 2021-09-14 16:35 UTC
Labels: bug
