### ISSUE TITLE
Bug[UI]: Missing Searchbar (Global suppliers)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#111] opened 2021-02-23 04:45 UTC
Context
- https://open-contracting.health/global-overview/data

Steps
- Data>> Global Suppliers

Actual result
- Doesn't contain a search bar.

Expected result
- Should contain a search bar.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108803066-da81a700-75c1-11eb-85ef-33f76ef70e84.png)
![image](https://user-images.githubusercontent.com/45354665/108803128-056bfb00-75c2-11eb-941d-ed64bc890a9d.png)

**Comment by nirazanbasnet** [comment] 2021-03-01 09:44
On hold at the moment the client will provide information for this @suhanapradhan

**Comment by jpmckinney** [comment] 2021-09-14 16:34
This is not a bug, but rather an unimplemented feature. I don't get the sense we will be implementing it, so closing.

**Closed by jpmckinney** 2021-09-14 16:34 UTC
Labels: bug
